import Foundation
import NibContracts

// `plugin.sdkTypes` (nib.d.ts from the live command registry) and `plugin.docs` (the authoring reference), both paged
// with a cursor like every read result over 20 KB (ARCHITECTURE.md §6.1).

// MARK: - Paging

struct TextPage: Codable, Equatable {
    var text: String
    var truncated: Bool
    /// Pass back unchanged to read the next page.
    var cursor: String?
    /// Characters before this page and in the whole text.
    var offset: Int
    var total: Int
}

enum TextPager {
    /// Keeps each page (plus its JSON wrapper) under the 20 KB result budget.
    static let pageSize = 12_000

    /// The page starting at `cursor` (a character offset from a previous page); pages end at a line break when one
    /// is near.
    static func page(_ text: String, cursor: String?, size: Int = pageSize) throws -> TextPage {
        let total = text.count
        var start = 0
        if let c = cursor, !c.isEmpty {
            guard let n = Int(c), n >= 0, n <= total else {
                throw NibError.invalid("unknown cursor '\(c)'", path: "$.cursor")
            }
            start = n
        }
        let from = text.index(text.startIndex, offsetBy: start)
        var to = text.index(from, offsetBy: size, limitedBy: text.endIndex) ?? text.endIndex
        if to < text.endIndex, let newline = text[from..<to].lastIndex(of: "\n"),
           text.distance(from: from, to: newline) > size / 2 {
            to = text.index(after: newline)
        }
        let chunk = String(text[from..<to])
        let end = start + chunk.count
        let more = end < total
        return TextPage(text: chunk, truncated: more, cursor: more ? String(end) : nil, offset: start, total: total)
    }
}

// MARK: - nib.d.ts

enum SDKTypesGenerator {
    /// TypeScript definitions for plugin authors: the static `nib` API (docs/PLUGIN_API.md §4) plus the params of every
    /// command a plugin may call, keyed by id, with typed overloads of `nib.commands.execute`, `nib.commands.batch` and
    /// `ctx.execute`.
    static func generate(_ commands: [CommandDescriptor]) -> String {
        var out = "// nib.d.ts — Nib plugin API v\(apiVersion). Generated by plugin.sdkTypes from the live command registry\n"
        out += "// (\(commands.count) commands a plugin can call). Regenerate after installing features or plugins.\n\n"
        out += staticAPI
        out += "\n/** Params of every command a plugin can call, by command id. */\n"
        out += "interface NibCommandParams {\n"
        for d in commands.sorted(by: { $0.id < $1.id }) {
            out += comment(for: d, indent: "  ")
            out += "  \(quote(d.id)): \(tsType(d.params, indent: "  "));\n"
        }
        out += "}\n\n"
        out += """
        declare namespace nib {
          type CommandId = keyof NibCommandParams;
          type CommandCall = { [K in keyof NibCommandParams]: { command: K; params?: NibCommandParams[K] } }[keyof NibCommandParams];
          namespace commands {
            function execute<K extends keyof NibCommandParams>(command: K, params?: NibCommandParams[K], opts?: { dryRun?: boolean; group?: string }): Promise<any>;
            function batch(calls: CommandCall[], opts?: { stopOnError?: boolean }): Promise<{ ok: boolean; value?: any; error?: NibError }[]>;
          }
          interface CallContext {
            execute<K extends keyof NibCommandParams>(command: K, params?: NibCommandParams[K], opts?: { dryRun?: boolean }): Promise<any>;
          }
        }

        """
        return out
    }

    static let apiVersion = 1

    static func comment(for d: CommandDescriptor, indent: String) -> String {
        var facts = ["effect: \(d.effect.rawValue)"]
        if d.destructive { facts.append("destructive") }
        let scopes = d.scopes.map { $0.rawValue }.sorted()
        if !scopes.isEmpty { facts.append("scopes: " + scopes.joined(separator: ", ")) }
        facts.append("owner: \(d.owner)")
        return "\(indent)/**\n\(indent) * \(sanitize(d.summary))\n\(indent) * \(facts.joined(separator: " · "))\n\(indent) */\n"
    }

    /// A TypeScript type for a flat schema (`raw` plugin schemas are read as JSON Schema).
    static func tsType(_ schema: JSONSchema, indent: String) -> String {
        switch schema {
        case let .object(properties, required, _):
            if properties.isEmpty { return "Record<string, unknown>" }
            let inner = indent + "  "
            var s = "{\n"
            for key in properties.keys.sorted() {
                guard let p = properties[key] else { continue }
                if let d = description(of: p) { s += "\(inner)/** \(sanitize(d)) */\n" }
                s += "\(inner)\(quote(key))\(required.contains(key) ? "" : "?"): \(tsType(p, indent: inner));\n"
            }
            return s + "\(indent)}"
        case let .array(items, _):
            let t = tsType(items, indent: indent)
            return t.contains(" | ") || t.hasPrefix("{") && t.contains("\n") ? "Array<\(t)>" : "\(t)[]"
        case let .string(_, choices):
            guard let c = choices, !c.isEmpty else { return "string" }
            return c.map { JSONValue.string($0).jsonString() }.joined(separator: " | ")
        case .number, .integer:
            return "number"
        case .boolean:
            return "boolean"
        case .anyValue:
            return "unknown"
        case .raw(let json):
            return tsType(SchemaConverter.schema(json), indent: indent)
        }
    }

    static func description(of schema: JSONSchema) -> String? {
        switch schema {
        case let .object(_, _, d), let .array(_, d): return d
        case let .string(d, _), let .number(d, _, _), let .boolean(d), let .anyValue(d): return d
        case let .integer(d, _, _): return d
        case .raw(let json): return json["description"]?.stringValue
        }
    }

    static func quote(_ key: String) -> String {
        if key.range(of: "^[A-Za-z_$][A-Za-z0-9_$]*$", options: .regularExpression) != nil { return key }
        return JSONValue.string(key).jsonString()
    }

    /// One line, safe inside a /** */ comment.
    static func sanitize(_ s: String) -> String {
        s.replacingOccurrences(of: "*/", with: "*\\/").components(separatedBy: .newlines).joined(separator: " ")
    }

    /// The hand-written part: the `nib` namespace of docs/PLUGIN_API.md §4.
    static let staticAPI = """
    declare namespace nib {
      /** This plugin. `settings` = current values of contributes.settings. */
      const plugin: { id: string; version: string; settings: Record<string, unknown> };

      interface NibError { code: string; message: string; path?: string; hint?: string }
      interface ChangeSummary { created: string[]; updated: string[]; removed: string[] }
      interface NibEvent {
        seq: number; type: string; at: number; principal?: string; doc?: string;
        changes?: ChangeSummary; payload?: any; truncated?: boolean;
      }
      /** query.context: where the user is (document, page, selection, tool, tabs). */
      interface Context {
        document?: { ref: string; id: string; kind: string; title?: string; [key: string]: any };
        page?: { ref: string; id: string; index: number; [key: string]: any };
        selection?: { refs: string[]; bbox?: number[]; [key: string]: any };
        tool?: string;
        [key: string]: any;
      }

      /** Passed to every handler. Calls made through ctx.execute share the caller's undo group (one Undo step). */
      interface CallContext {
        /** Undo group of this invocation. */
        group: string;
        /** "plugin:<id>". */
        principal: string;
        /** True in ask mode and inside commands declared "read": every execute must then be a read command. */
        readOnly: boolean;
        execute<T = any>(command: string, params?: object, opts?: { dryRun?: boolean }): Promise<T>;
      }

      namespace commands {
        /** Run any command (built-in, feature or another plugin's). A fresh undo group unless called via ctx. */
        function execute<T = any>(command: string, params?: object, opts?: { dryRun?: boolean; group?: string }): Promise<T>;
        /** Several commands in order as ONE undo step (commands.batch). */
        function batch(calls: { command: string; params?: object }[], opts?: { stopOnError?: boolean }):
          Promise<{ ok: boolean; value?: any; error?: NibError }[]>;
        /** Implement a command declared in manifest.contributes.commands. */
        function register(id: string, handler: (params: any, ctx: CallContext) => unknown | Promise<unknown>): void;
        function list(namespace?: string): Promise<{ id: string; title: string; summary: string; effect: string; destructive: boolean }[]>;
        function describe(id: string): Promise<{ id: string; params: object; examples: object[]; effect: string; scopes: string[] }>;
      }

      /** Sugar over the read commands (query.*, search.text, recognize.*, render.page). */
      namespace query {
        function context(): Promise<Context>;
        function tree(root?: string, depth?: number): Promise<any>;
        function get(ref: string, opts?: { depth?: number; points?: boolean; fields?: string[] }): Promise<any>;
        function find(filter: { in: string; kinds?: string[]; layer?: number; bbox?: number[];
                                where?: object; text?: string; limit?: number; cursor?: string }): Promise<{ items: any[]; cursor?: string }>;
        function search(text: string, scope?: string): Promise<any[]>;
        function pageText(page: string): Promise<{ blocks: { text: string; bbox: number[]; source: string; itemIDs: string[] }[] }>;
        /** render.page: a temporary PNG ("tmp:<name>", long edge ≤ 1568 px); marks number the items. */
        function render(page: string, opts?: { scale?: number; region?: number[]; marks?: boolean }):
          Promise<{ asset: string; pxPerPt: number; region: number[]; marks?: Record<string, string> }>;
      }

      namespace canvas {
        /** Transient DisplayList overlay on a page (canvas.decorate), removed after ttl seconds (default 5) or clear(). */
        function decorate(page: string, display: { ops: object[] }, opts?: { id?: string; ttl?: number }): Promise<string>;
        function clear(id?: string): Promise<void>;
      }

      namespace events {
        /** Subscribe; returns an unsubscribe function. Coalesced (≤ 1 per 100 ms per type); own events skipped unless filter.self. */
        function on(type: string, fn: (e: NibEvent, ctx: CallContext) => void, filter?: { doc?: string; self?: boolean }): () => void;
      }

      namespace ui {
        function toast(message: string): void;
        function confirm(title: string, message?: string): Promise<boolean>;
        function prompt(title: string, placeholder?: string, initial?: string): Promise<string | null>;
        function choose(title: string, options: string[]): Promise<number | null>;
        /** One of contributes.panels. */
        function openPanel(id: string): Promise<void>;
        /** Delivered to window.nib.onMessage in the panel. */
        function postToPanel(id: string, message: unknown): void;
      }

      /** Per plugin, JSON values, ≤ 5 MB, syncs with the library (outside the hashed plugin folder). */
      namespace storage {
        function get<T = unknown>(key: string): Promise<T | undefined>;
        function set(key: string, value: unknown): Promise<void>;
        function remove(key: string): Promise<void>;
        function keys(): Promise<string[]>;
      }

      /** Any setting; "plugin.<id>.*" = this plugin's own ("security.*" → permission_denied). */
      namespace settings {
        function get<T = unknown>(name: string): Promise<T | undefined>;
        function set(name: string, value: unknown): Promise<void>;
      }

      namespace assets {
        /** Store bytes in a document; returns an AssetRef name. `url` must be https or a tmp: ref. */
        function put(doc: string, data: { base64?: string; url?: string; text?: string }, ext: string): Promise<string>;
        /** asset.upload: a temporary asset ("tmp:<name>", 1 h) that url-taking commands accept. */
        function upload(data: { base64?: string; text?: string }, ext: string): Promise<string>;
        function url(doc: string, asset: string): Promise<string>;
      }

      /** Needs "ai"; tool calls run as this plugin. */
      namespace ai {
        function complete(req: { system?: string; messages: { role: "user" | "assistant"; text: string; images?: string[] }[];
                                 tools?: string[]; mode?: "ask" | "edit"; maxSteps?: number; json?: boolean }):
          Promise<{ text: string; group?: string; changes: ChangeSummary }>;
      }

      /** Needs "network" + the host in manifest.network.hosts. */
      namespace net {
        function fetch(url: string, init?: { method?: string; headers?: Record<string, string>; body?: string; bodyBase64?: string }):
          Promise<{ status: number; headers: Record<string, string>; text: string; base64?: string }>;
      }
    }
    // Globals: console.log/warn/error (→ plugin logs), setTimeout/clearTimeout/setInterval/clearInterval,
    // structuredClone (JSON), TextEncoder/TextDecoder, atob/btoa. No fetch, XMLHttpRequest, require or file system.

    """
}

// MARK: - plugin.docs

enum PluginDocs {
    /// The authoring reference: manifest rules and schema, permissions, every contribution point, the JavaScript API,
    /// events, limits and the AI authoring loop. Built from the same tables the validator and the mapper use.
    static func markdown() -> String {
        var s = """
        # Nib plugin reference (API v\(SDKTypesGenerator.apiVersion))

        A plugin is JavaScript that runs inside Nib (JavaScriptCore). It does what a user can do by hand by calling the
        same commands the UI uses, within the permissions the user granted. Every command a plugin registers also
        becomes an AI and bridge tool unless it opts out (`ai: false` / `bridge: false`).

        Call `plugin.sdkTypes` for exact TypeScript definitions of every command you can call.

        ## Package

        A folder (or a `.nibplugin` zip) with `manifest.json`, ONE bundled script (`entry`, an IIFE; no module loader),
        and optional HTML panels, templates and assets. It is installed to `<Library>/\(NibFormat.libraryDirectory)/plugins/<id>/`. The
        user's grant is device-local and bound to the sha256 of that folder (sorted relative paths + contents; hidden
        files ignored), so a plugin that changes on disk or arrives through sync needs review before it runs again.
        `nib.storage` lives outside the folder and never invalidates the grant.

        ## Manifest

        | Field | Rules |
        |---|---|
        | id | Reverse-DNS `[a-z0-9.-]` with at least one dot; equals the folder name; owns everything the plugin registers. |
        | name | Shown to the user. |
        | version | semver, e.g. 1.2.0. An update that adds permissions asks for consent again. |
        | api | 1. |
        | entry | Relative path of the JS bundle inside the folder; evaluated once when the plugin starts. |
        | permissions | Scopes below. Anything not listed is denied at call time with permission_denied. |
        | network.hosts | Host names for `nib.net.fetch` and panels; honoured only with "network". |
        | contributes | Contribution points below; every field optional. |

        Every id a plugin contributes (commands, toolbar items, tools, panels, templates, stroke processors, element
        collections, tape patterns, board templates) starts with `<plugin id>.`.

        ## Permissions

        | Permission | Allows |
        |---|---|
        | document:read | Reading documents (query, search, render, recognize). |
        | document:write | Editing documents (ink, items, pages, text). |
        | library:read | Listing folders and documents. |
        | library:write | Creating, moving, renaming and trashing documents and folders; installing elements and templates. |
        | destructive | Deleting, overwriting and clearing. |
        | app | Session and app commands (tool selection, panels, settings, view). |
        | ai | nib.ai.complete with the user's AI provider. |
        | network | nib.net.fetch and panel requests to network.hosts. |

        `plugins:manage` and `security` are never granted. Irreversible commands always ask the user.

        ## Contribution points

        ### commands
        `{id, title, summary, params?, examples?, effect?, target?, destructive?, ai?, bridge?, aiDirect?, longRunning?}`.
        `effect` is read | session | edit | library | irreversible (default edit), `target` document | library | app
        (default document); together with `destructive` they decide the scopes a caller needs. A command declared `read`
        runs read-only: anything its handler executes must be a read command, or the call fails with permission_denied.
        `params` is a JSON Schema object (types, required, enum, minimum/maximum are enforced for the AI, the bridge and
        other plugins). Give at least one example when the command is exposed to AI. Implement it with
        `nib.commands.register(id, handler)`; everything the handler does through `ctx.execute` is one undo step.
        `longRunning` allows 300 s instead of 30 s. `ai: false` / `bridge: false` hide it from those callers (the user can
        override with Settings › Plugins › Expose hidden plugin commands). `aiDirect: true` gives it its own AI tool.

        ### menus
        `{location, command, title?, icon?, when?: {selectionKinds?, minSelection?, docKinds?}}`. Locations:
        \(MenuLocation.allCases.map { $0.rawValue }.joined(separator: ", ")).
        `when.selectionKinds`: every selected item is one of these kinds (\(ItemKind.allCases.map { $0.rawValue }.joined(separator: ", "))).
        `when.docKinds`: \(DocumentKind.allCases.map { $0.rawValue }.joined(separator: ", ")).
        The command receives the menu context: `{doc, page, point, selection, nodes, ref, index, folder, range}`.

        ### toolbar
        `{id, title, icon, group?, command | tool}`; group is tools, accessories (default), navLeading or navTrailing.
        Command buttons receive `{doc, page}` of their window. Users can hide and reorder plugin buttons.

        ### tools and toolOptions
        `tools: [{id, title, icon?, input, preview?, sticky?, command}]`. JavaScript never runs per Pencil sample: the host
        captures the input, draws the preview and calls the command once. input `stroke` → `{page, pts: [x, y, …], fmt: "xy",
        bbox}` on lift (preview ink | lasso | none); `tap` → `{page, point}`; `rect` → `{page, rect}` (dashed rectangle).
        `toolOptions: [{tool, settings: [keys of contributes.settings]}]` shows an options bar (a form over those settings)
        while the tool is active.

        ### panels
        `{id, title, icon?, entry, placement?}`; placement \(PanelPlacement.allCases.map { $0.rawValue }.joined(separator: ", ")) (default
        floating). The panel is a WKWebView from `nib-plugin://<id>/<entry>` with the same `window.nib` API, plus
        `nib.onMessage(fn)` and `nib.postMessage(msg)` (a plugin.message event for main.js). No network outside
        `network.hosts`, and none without "network".

        ### templates
        `{id, title, category?, kind: "spec" | "pdf", isCover?, params?, spec?, file?, size?: {width, height}}`.
        `spec: {paper?, ops: [DisplayOp]}` with op one of \(DisplayOpKind.allCases.map { $0.rawValue }.joined(separator: ", ")) and the DisplayOp
        fields rect [x, y, w, h], points [[x, y]], stroke, fill (#RRGGBBAA), width, dash, text, fontSize, fontName, asset,
        spacing, radius, align, weight. A string "$name" anywhere in spec is replaced by that parameter's value.
        `params: {"name": {"type": "number" | "color" | "choice" | "bool", "default", "choices"?, "title"?, "min"?, "max"?}}`.
        Ops are drawn at `size` and scaled to other page sizes. `kind: "pdf"` with `file` uses the PDF's first page (its
        vector paths and text). `isCover: true` lists it under Covers.

        ### keybindings
        `{key, command, title?}`: key like cmd+shift+f, alt+1, ctrl+option+left (modifiers cmd, shift, alt/option, ctrl;
        named keys up, down, left, right, escape, delete, tab, return, space). A key without cmd, alt or ctrl only works on
        the canvas.

        ### settings
        A JSON Schema object; its properties become an auto-generated settings page (boolean → switch, enum → picker,
        number with minimum and maximum → slider, format "color" → colour well, other strings → text, anything else →
        JSON). Values are the settings `plugin.<id>.<key>` (synced with the library) and `nib.plugin.settings`.

        ### aiActions and ai
        `aiActions: [{title, prompt, scope?, mode?, icon?}]` adds a chip to the AI panel (scope \(AIScopeKind.allCases.map { $0.rawValue }.joined(separator: ", ")); mode
        ask | edit). `ai: {instructions}` (≤ 1,000 characters) is appended to the AI system prompt while the plugin runs.

        ### importers and exporters
        `{extensions, command, title?}`. An importer's command gets `{asset: "tmp:<name>", name, target: {folder?, doc?,
        position, anchor?, ids?}}` and returns the refs it created. An exporter's command gets `{docs, pages?, options,
        fileName?}` and returns `{files: [{name, base64 | text}]}`.

        ### itemTypes
        `{type, title, edit?, inspector?, textPath?}`: `custom` items `{owner: "<plugin id>", type, frame, data, display}`.
        The host always draws `display` (a DisplayList relative to `frame`), so items survive uninstall. Double-tapping one
        calls `edit` with `{ref}`. `inspector` (a JSON Schema over `data`) is shown when the item is selected and writes
        through item.update. `textPath` (a dot path into `data`) is searchable and read by recognition and VoiceOver.

        ### tapHandlers
        `{gesture: "tap" | "doubleTap" | "longPress", command, itemKinds?, itemTypes?}`: finger gestures on the canvas go to
        the command with `{page, point, ref?, gesture}` before the active tool; return `{handled: true}` to consume it.

        ### blocks
        `{type, title, icon?, height?, command, aliases?}` adds a text-document block kind to the slash and Turn Into menus.
        Blocks are `custom` blocks `{owner, type, height, data, display}`; the command gets `{doc, after?}` to insert and
        `{ref}` when the block is tapped.

        ### strokeProcessors
        `{id, command, tools?}` (tools default pen, pencil, highlighter): the command runs once per finished stroke with
        `{page, stroke}` and returns `{stroke}` (changed) or `{drop: true}`. Budget 50 ms; on timeout or error the stroke
        is kept as drawn.

        ### pencilActions
        `{gesture: "doubleTap" | "squeeze", command, title}`: offered in Settings › Apple Pencil. The command gets
        `{gesture, doc, page?, at?}`.

        ### commandHooks
        `{commands: ["page.add", "export.*"], command}`: before each matching call (from anyone) the hook command, which
        must be declared `read`, gets `{command, params}` and returns `{}` to let it pass, `{params}` to change the params,
        or throws to veto it. Hooks never see plugin management or security calls.

        ### Content packs
        `elements: [{id, title, files}]` (each file a clipboard fragment `{format: "nib-fragment/1", items, assets,
        bounds}` or an array of `{id, title, fragment}`), `tapePatterns: [{id, title, file}]` (~100 px PNG tiles),
        `boardTemplates: [{id, title, icon?, diagram | file}]` (a diagram.create spec without page, or a fragment file),
        and `templates` with `isCover`.

        ## JavaScript API

        `nib.plugin`, `nib.commands` (execute, batch, register, list, describe), `nib.query` (context, tree, get, find,
        search, pageText, render), `nib.canvas` (decorate, clear), `nib.events.on`, `nib.ui` (toast, confirm, prompt,
        choose, openPanel, postToPanel), `nib.storage` (get, set, remove, keys), `nib.settings` (get, set), `nib.assets`
        (put, upload, url), `nib.ai.complete`, `nib.net.fetch`. Calls return Promises and reject with
        `{code, message, path?, hint?}` (codes: \(NibError.Code.allCases.map { $0.rawValue }.joined(separator: ", "))).
        Globals: console, timers, structuredClone, TextEncoder/TextDecoder, atob/btoa; no fetch, XMLHttpRequest, require or
        file system (commands take tmp: refs from nib.assets.upload or https URLs).

        ## Events

        tx.committed, doc.opened, doc.closed, session.document, page.changed, tool.changed, selection.changed,
        library.changed, ai.turn.finished, plugin.message, sync.status, laser.moved, backup.status. Events carry refs, not
        content; query what you need.

        ## Limits

        Bundle ≤ 20 MB; nib.storage ≤ 5 MB; one call ≤ 30 s (300 s with longRunning); nested command depth ≤ 16; stroke
        processors 50 ms; ai.instructions ≤ 1,000 characters. A plugin that blocks past its timeout is marked unresponsive
        and its calls are rejected; in Safe Mode no plugin runs.

        ## Writing a plugin with the AI or the bridge

        1. Read this reference and `plugin.sdkTypes`.
        2. `plugin.install {files: {"manifest.json": "…", "main.js": "…"}}` (always confirmed; the user sees the code).
        3. Iterate with `commands.batch`/any command with `dryRun`, `plugin.logs {id}` and `plugin.reload {id}`.

        Plugins themselves can never install, enable or reload plugins.

        ## Manifest JSON Schema

        ```json

        """
        s += manifestSchema.jsonString(pretty: true)
        s += "\n```\n"
        return s
    }

    /// JSON Schema of manifest.json.
    static let manifestSchema: JSONValue = {
        let text = #"""
        {"$schema": "https://json-schema.org/draft/2020-12/schema", "title": "Nib plugin manifest", "type": "object",
         "required": ["id", "name", "version", "api", "entry", "permissions"],
         "properties": {
          "id": {"type": "string", "pattern": "^[a-z0-9]+([.-][a-z0-9]+)*$"},
          "name": {"type": "string"}, "version": {"type": "string"}, "api": {"const": 1},
          "author": {"type": "string"}, "description": {"type": "string"}, "homepage": {"type": "string"},
          "entry": {"type": "string"},
          "permissions": {"type": "array", "items": {"enum": ["document:read", "document:write", "library:read", "library:write", "destructive", "app", "ai", "network"]}},
          "network": {"type": "object", "properties": {"hosts": {"type": "array", "items": {"type": "string"}}}},
          "contributes": {"type": "object", "properties": {
           "commands": {"type": "array", "items": {"type": "object", "required": ["id", "title", "summary"], "properties": {
             "id": {"type": "string"}, "title": {"type": "string"}, "summary": {"type": "string"}, "params": {"type": "object"},
             "examples": {"type": "array", "items": {"type": "object"}},
             "effect": {"enum": ["read", "session", "edit", "library", "irreversible"]}, "target": {"enum": ["document", "library", "app"]},
             "destructive": {"type": "boolean"}, "ai": {"type": "boolean"}, "bridge": {"type": "boolean"},
             "aiDirect": {"type": "boolean"}, "longRunning": {"type": "boolean"}}}},
           "menus": {"type": "array", "items": {"type": "object", "required": ["location", "command"], "properties": {
             "location": {"type": "string"}, "command": {"type": "string"}, "title": {"type": "string"}, "icon": {"type": "string"},
             "when": {"type": "object", "properties": {"selectionKinds": {"type": "array", "items": {"type": "string"}},
               "minSelection": {"type": "integer", "minimum": 0}, "docKinds": {"type": "array", "items": {"type": "string"}}}}}}},
           "toolbar": {"type": "array", "items": {"type": "object", "required": ["id", "title", "icon"], "properties": {
             "id": {"type": "string"}, "title": {"type": "string"}, "icon": {"type": "string"},
             "group": {"enum": ["tools", "accessories", "navLeading", "navTrailing"]}, "command": {"type": "string"}, "tool": {"type": "string"}}}},
           "tools": {"type": "array", "items": {"type": "object", "required": ["id", "title", "input", "command"], "properties": {
             "id": {"type": "string"}, "title": {"type": "string"}, "icon": {"type": "string"}, "input": {"enum": ["stroke", "tap", "rect"]},
             "preview": {"enum": ["ink", "lasso", "none"]}, "sticky": {"type": "boolean"}, "command": {"type": "string"}}}},
           "toolOptions": {"type": "array", "items": {"type": "object", "required": ["tool", "settings"], "properties": {
             "tool": {"type": "string"}, "settings": {"type": "array", "items": {"type": "string"}}}}},
           "panels": {"type": "array", "items": {"type": "object", "required": ["id", "title", "entry"], "properties": {
             "id": {"type": "string"}, "title": {"type": "string"}, "icon": {"type": "string"}, "entry": {"type": "string"},
             "placement": {"enum": ["sidebarTab", "floating", "sheet", "libraryTab", "fullScreen"]}}}},
           "templates": {"type": "array", "items": {"type": "object", "required": ["id", "title", "kind"], "properties": {
             "id": {"type": "string"}, "title": {"type": "string"}, "category": {"type": "string"}, "kind": {"enum": ["spec", "pdf"]},
             "isCover": {"type": "boolean"}, "params": {"type": "object"}, "spec": {"type": "object"}, "file": {"type": "string"},
             "size": {"type": "object", "properties": {"width": {"type": "number"}, "height": {"type": "number"}}}}}},
           "keybindings": {"type": "array", "items": {"type": "object", "required": ["key", "command"], "properties": {
             "key": {"type": "string"}, "command": {"type": "string"}, "title": {"type": "string"}}}},
           "settings": {"type": "object"},
           "aiActions": {"type": "array", "items": {"type": "object", "required": ["title", "prompt"], "properties": {
             "title": {"type": "string"}, "prompt": {"type": "string"}, "scope": {"type": "string"}, "mode": {"enum": ["ask", "edit"]},
             "icon": {"type": "string"}}}},
           "ai": {"type": "object", "properties": {"instructions": {"type": "string", "maxLength": 1000}}},
           "importers": {"type": "array", "items": {"type": "object", "required": ["extensions", "command"], "properties": {
             "extensions": {"type": "array", "items": {"type": "string"}}, "command": {"type": "string"}, "title": {"type": "string"}}}},
           "exporters": {"type": "array", "items": {"type": "object", "required": ["extensions", "command"], "properties": {
             "extensions": {"type": "array", "items": {"type": "string"}}, "command": {"type": "string"}, "title": {"type": "string"}}}},
           "itemTypes": {"type": "array", "items": {"type": "object", "required": ["type", "title"], "properties": {
             "type": {"type": "string"}, "title": {"type": "string"}, "edit": {"type": "string"}, "inspector": {"type": "object"},
             "textPath": {"type": "string"}}}},
           "tapHandlers": {"type": "array", "items": {"type": "object", "required": ["gesture", "command"], "properties": {
             "gesture": {"enum": ["tap", "doubleTap", "longPress"]}, "command": {"type": "string"},
             "itemKinds": {"type": "array", "items": {"type": "string"}}, "itemTypes": {"type": "array", "items": {"type": "string"}}}}},
           "blocks": {"type": "array", "items": {"type": "object", "required": ["type", "title", "command"], "properties": {
             "type": {"type": "string"}, "title": {"type": "string"}, "icon": {"type": "string"}, "height": {"type": "number"},
             "command": {"type": "string"}, "aliases": {"type": "array", "items": {"type": "string"}}}}},
           "strokeProcessors": {"type": "array", "items": {"type": "object", "required": ["id", "command"], "properties": {
             "id": {"type": "string"}, "command": {"type": "string"}, "tools": {"type": "array", "items": {"enum": ["pen", "pencil", "highlighter", "tape"]}}}}},
           "pencilActions": {"type": "array", "items": {"type": "object", "required": ["gesture", "command", "title"], "properties": {
             "gesture": {"enum": ["doubleTap", "squeeze"]}, "command": {"type": "string"}, "title": {"type": "string"}}}},
           "commandHooks": {"type": "array", "items": {"type": "object", "required": ["commands", "command"], "properties": {
             "commands": {"type": "array", "items": {"type": "string"}}, "command": {"type": "string"}}}},
           "elements": {"type": "array", "items": {"type": "object", "required": ["id", "title", "files"], "properties": {
             "id": {"type": "string"}, "title": {"type": "string"}, "files": {"type": "array", "items": {"type": "string"}}}}},
           "tapePatterns": {"type": "array", "items": {"type": "object", "required": ["id", "title", "file"], "properties": {
             "id": {"type": "string"}, "title": {"type": "string"}, "file": {"type": "string"}}}},
           "boardTemplates": {"type": "array", "items": {"type": "object", "required": ["id", "title"], "properties": {
             "id": {"type": "string"}, "title": {"type": "string"}, "icon": {"type": "string"}, "diagram": {"type": "object"},
             "file": {"type": "string"}}}}
          }}
         }}
        """#
        return (try? JSONValue.parse(text)) ?? .null
    }()
}
